name: Deploy React Portfolio
on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        # We use --legacy-peer-deps to ignore version conflicts
        run: npm install --legacy-peer-deps

      - name: Check if folder exists
        # This will tell us if react-scripts actually installed
        run: ls -la node_modules/.bin/react-scripts

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4